### ISSUE TITLE
dan model

### ISSUE THREAD

**Issue by qiming111** [Lab41/Magnolia#85]
Excuse me.I can't find the libritrain='/home/ai/matlab2016b/Magnolia-master/data/librispeech/authors/processed_train-clean-100.h5' file.

**Comment by karllab41** [comment]
Hi Qiming-

The data "processed_train-clean-100.h5" is our training set, which we created from folders in:

https://github.com/Lab41/Magnolia/tree/master/src/features

You need to create the training set there. You can access a notebook in there called:

https://github.com/Lab41/Magnolia/blob/master/src/features/preprocessing_example.ipynb

for an example. Once you create that file, you'll be able to run your models.

Please let us know if that works...

-Karl

**Comment by karllab41** [comment]
Closing this issue; please let us know if you'd like us to reopen it.
