### ISSUE TITLE
Error in running preprocess_data

### ISSUE THREAD

**Issue by raikar008** [Lab41/Magnolia#99]
![screenshot from 2017-11-07 20-48-42](https://user-images.githubusercontent.com/26719772/32501113-27dbc0fa-c3fd-11e7-921a-47d56e26fab5.png)

**Comment by jhetherly** [comment]
This seems like an issue with the audioread backend that librosa needs. If you install librosa with the `conda` command like so: `conda install -c conda-forge librosa`, then this issue may go away. The repo is in need of a restructuring overhaul and extensive documentation. Thus, I apologize if the scripts aren't yet robust or the instructions aren't clear.

**Comment by raikar008** [comment]
It worked! Thanks. This repo is awesome and is really helping in my research. I have just started my research, I might have more doubts further as I am very new in this work. Thanks again.

**Comment by jhetherly** [comment]
Great to hear! I'm closing this for now and I'll reopen if necessary.
